[book]
title = "Personal Calendar"
authors = ["Inno-Cringineers"]
language = "en"
multilingual = false
src = "docs"

[output.html]
default-theme = "navy"
preferred-dark-theme = "navy"

[output.linkcheck]
follow-web-links = true
traverse-parent-directories = true
warn-on-missing-ids = true

