[book]
title = "Personal Calendar"
authors = ["Inno-Cringineers"]
language = "en"
multilingual = false
src = "docs"

[output.html]
default-theme = "navy"
preferred-dark-theme = "navy"
# Set base URL for GitHub Pages
site-url = "https://inno-cringineers.github.io/Telegram_Calendar/"

[output.linkcheck]
follow-web-links = false
traverse-parent-directories = true
warn-on-missing-ids = true

