services:
  bot:
    build: .
    container_name: bot-prod
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
    restart: unless-stopped
    volumes:
      - ./src:/app/src

# TODO: volume for database
# TODO: volume for logs
