title: "Personal calendar"
description: "Self-hosted Telegram bot for event management with reminders and calendar integration. "
theme: minima
baseurl: "/Telegram_Calendar" 
url: "https://Inno-Cringineers.github.io" 