# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: Lint docs with Lychee Link Checker

on:
    push:
        paths: ["docs/**", ".github/workflows/**"]

jobs:
    # Link check job
    linkcheck:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Lychee Link Checker
              uses: lycheeverse/lychee-action@v1
              with:
                  args: "--accept 200,429 ./docs/**/*.md"
                  fail: true
